#!/bin/bash

#This script is just to create a simulated production context in 
#which launchclient will send a client into production. It create 
#the ckan src is already installed and the default development.ini
#file as well, but none of the necessary configurations have taken
#place,  solr has not been started and who.ini has not been linked
#these have to be dealt with now on a multitenant machine 

#Check whether we're using a volume copied from prod
#that doesn't need formatting
#Mount external filestore
echo "Enter the three letter device identifier for the volume to mount (n if you don't know):"
read volID

if [ ${volID} = "n" ] #give user an out if they don't have the dev id
then
	echo 'Run sudo fdisk -l to view attached devices'
	exit 1
fi

#Check whether we're using a volume copied from prod
#that doesn't need formatting
echo "Does the volume require formatting(y/n)?"
read reqfrmt
if [ ${reqfrmt} = "y" ]
then
	sudo mkfs -t ext4 /dev/${volID}
	echo 'Formatting device $volID as ext4'
fi

#mount the volume
sudo mkdir /FSTORE
sudo mount /dev/${volID} /FSTORE

echo "Have you created the ckan_default database user and schema with password on the database server?(y/n)"
read confirmdb
if [ ${confirmdb} = "n" ]
then
	echo 'Please create the database user, schema and password on the database server before continuing.'
	exit 1
fi

echo "Enter the local subnet fixed ip for the database server: (n if unknown)"
read $dbserv
if [ ${dbserv} = "n" ]
then
	echo "Please confirm the database server's fixed ip before continuing."
	exit 1
fi

#Install apache and nginx
sudo apt-get install -y apache2 libapache2-mod-wsgi nginx

#TO-DO HOW TO INSTALL POSTFIX FROM COMMAND LINE AND CONFIGURE


#Put nginx and apache configuration files in place
sudo cp ./ogg-proxy /etc/nginx/sites-available/.
sudo ln /etc/nginx/sites-available/ogg-proxy /etc/nginx/sites-enabled/ogg-proxy
sudo rm /etc/nginx/sites-enabled/default

sudo sed 's/80/8080/' /etc/apache2/ports.conf
sudo cp ./ckan_default /etc/apache2/sites-available/. 
sudo ln -s /usr/lib/ckan/ckan_default/src/ckan/who.ini /etc/ckan/ckan_default/who.ini
sudo ln -s /usr/lib/ckan/ckan_default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml #TO-DO maybe change this to work with multicore solr

#customize development.ini configuration
cd /etc/ckan/ckan_default
sudo sed -i s/ckan_default/ckan_default/ development.ini #user for postgres connection
sudo sed -i s/pass/capstone/ development.ini #password for postgres connection
sudo sed -i s_@localhost/_@${dbserv}/_ development.ini #password for postgres connection
sudo sed -i s/ckan_default/ckan_default_db/ development.ini #table schema
#sudo sed -i s/ckan\.site_url=/ckan\.site_url = http:\/\/${hostIP}/ development.ini #this command doesn't work
sudo sed -i s/CKAN/ckan_default/ development.ini #site_title wish we could make it all caps or capinit
sudo sed -i 's/#solr_url/solr_url/' /etc/ckan/default/development.ini #activate solr
sudo sed -i 's/#ckan\.storage_path/ckan\.storage_path/' development.ini #activate file store
sudo sed -i s_/var/lib/ckan_/FSTORE/ckan_default_ development.ini #set file store location

#initialise file store
sudo mkdir -p /FSTORE/ckan_default
sudo chown `whoami` /FSTORE/ckan_default #paster runs under the id of 
					#whatever user started it
sudo chmod u+rwx /FSTORE/ckan_default #because the user guide says so

#enable CKAN solr search platform on jetty and start
sudo mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak
sudo ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml
sudo service jetty start

#create client database user, password and schema and initialise db
sudo -u postgres createuser -S -D -R ckan_default
sudo -u postgres psql -U postgres -d postgres -c "alter user ckan_default with password 'capstone';"
sudo -u postgres createdb -O ckan_default ckan_default_db -E utf-8
cd /usr/lib/ckan/ckan_default/src/ckan
. /usr/lib/ckan/default/bin/activate
paster db init -c /etc/ckan/ckan_default/development.ini

cd /usr/lib/ckan/default/src/ckan
sudo cp /etc/ckan/default/development.ini /etc/ckan/default/production.ini

sudo a2ensite ckan_default
sudo service apache2 start
sudo service nginx reload
