#!/bin/bash
#Ckan Install V2
# 
# 

#sudo apt-get update
#sudo apt-get install -y python-dev postgresql libpq-dev python-pip python-virtualenv git-core solr-jetty openjdk-6-jdk
#sudo mkdir -p /usr/lib/ckan/default
#sudo chown `whoami` /usr/lib/ckan/default
#virtualenv /usr/lib/ckan/default
#. /usr/lib/ckan/default/bin/activate
#pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.2#egg=ckan'
#pip install -r /usr/lib/ckan/default/src/ckan/requirements.txt
#deactivate
. /usr/lib/ckan/default/bin/activate
sudo -u postgres createuser -S -D -R ckan_default
sudo -u postgres psql -U postgres -d postgres -c "alter user ckan_default with password 'capstone';"
sudo -u postgres createdb -O ckan_default ckan_default -E utf-8
sudo mkdir -p /etc/ckan/default
sudo chown -R `whoami` /etc/ckan/
cd /usr/lib/ckan/default/src/ckan
paster make-config ckan /etc/ckan/default/development.ini
cd /etc/ckan/default
sed -i 's/pass/capstone/' development.ini
cd /etc/default
sudo sed -i 's/NO_START=1/NO_START=0/' jetty
sudo sed -i 's/#JETTY_HOST=/JETTY_HOST=127.0.0.1 #/' jetty
sudo sed -i 's/#JETTY_PORT=8080/JETTY_PORT=8983/' jetty
sudo sed -i 's/#JAVA_HOME=/JAVA_HOME=\/usr\/lib\/jvm\/java-6-openjdk-amd64\//' jetty

sudo mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak
sudo ln -s /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml
sudo service jetty start
cd /etc/ckan/default
sudo sed -i 's/#solr_url/solr_url/' development.ini


#you need to change this line to your ip address
#sudo sed -i 's/ckan\.site_url=/ckan\.site_url = http://54.187.59.131/' development.ini 


cd /usr/lib/ckan/default/src/ckan
paster db init -c /etc/ckan/default/development.ini
#paster sysadmin add ogg-one -c /etc/ckan/default/development.ini

sudo mkdir -p /var/lib/ckan/default
sudo chown www-data /var/lib/ckan/default
sudo chmod u+rwx /var/lib/ckan/default

cd /etc/ckan/default
sudo sed -i 's/#ckan\.storage_path/ckan\.storage_path/' development.ini
sudo sed -i 's/\/var\/lib\/ckan/\/var\/lib\/ckan\/default/' development.ini

ln -s /usr/lib/ckan/default/src/ckan/who.ini /etc/ckan/default/who.ini
cd /usr/lib/ckan/default/src/ckan
#paster serve /etc/ckan/default/development.ini
sudo cp /etc/ckan/default/development.ini /etc/ckan/default/production.ini
sudo a2ensite ckan_default
sudo service apache2 start
sudo service nginx reload
