#!/usr/bin/env bash

#Configure

echo "Enter client organization's name:"
read orgName

#echo "Enter the road the client organization's main office is on:"
#read orgPswd

echo "Enter the host ip address:"
read hostIP

echo "Enter the database ip address:"
read dbserv


#Make source directory

sudo cp -r /usr/lib/ckan/default /usr/lib/ckan/${orgName}


#Make database

sudo -u postgres createuser -S -D -R ${orgName}_guy
sudo -u postgres psql -U postgres -d postgres -c "alter user ${orgName}_guy with password 'capstone';"
sudo -u postgres createdb -O ${orgName}_guy ${orgName}_cat -E utf-8


#Make configuration directory

sudo mkdir -p /etc/ckan/${orgName}
sudo chown -R `whoami` /etc/ckan/


#Make storage directory

sudo mkdir -p /var/lib/ckan/${orgName}/storage
sudo chmod 777 /var/lib/ckan/${orgName}/storage


#Make configuration file

cd /usr/lib/ckan/${orgName}/src/ckan
. /usr/lib/ckan/${orgName}/bin/activate
paster make-config ckan /etc/ckan/${orgName}/development.ini


#Setup solr

cd /etc/default
sudo sed -i 's/NO_START=1/NO_START=0/' jetty
sudo sed -i 's/#JETTY_HOST=/JETTY_HOST=127.0.0.1 #/' jetty
sudo sed -i 's/#JETTY_PORT=8080/JETTY_PORT=8983/' jetty
sudo sed -i 's/#JAVA_HOME=/JAVA_HOME=\/usr\/lib\/jvm\/java-6-openjdk-amd64\//' jetty
sudo mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak
sudo ln -s /usr/lib/ckan/${orgName}/src/ckan/ckan/config/solr/schema.xml /etc/solr/conf/schema.xml
sudo service jetty start


#Apply configurations

cd /etc/ckan/${orgName}
sed -i s/ckan_default/${orgName}_guy/ development.ini
sed -i s/pass/capstone/ development.ini
sed -i s/ckan_default/${orgName}_cat/ development.ini
sudo sed -i 's/#solr_url/solr_url/' development.ini
#sudo sed -i s/ckan\.site_url=/ckan\.site_url = http:\/\/${hostIP}/ development.ini 
sudo sed -i s/CKAN/${orgName}/ development.ini 
sudo sed -i 's/#ckan\.storage_path/ckan\.storage_path/' development.ini
sudo sed -i s_/var/lib/ckan_/var/lib/ckan/${orgName}_ development.ini


#Initialize DB tables

cd /usr/lib/ckan/${orgName}/src/ckan
paster db init -c /etc/ckan/${orgName}/development.ini


#Copy who.ini file

cd /etc/ckan/${orgName}
ln -s /usr/lib/ckan/${orgName}/src/ckan/who.ini /etc/ckan/${orgName}/who.ini


#Serve instance

cd /usr/lib/ckan/${orgName}/src/ckan
paster serve /etc/ckan/${orgName}/development.ini
